### ISSUE TITLE
Choosing spectral and isochrone libraries (Windows)

### ISSUE THREAD

**Issue by cylammarco** [dfm/python-fsps#174]
How can I switch the libraries in Windows PowerShell? It is not possible to use

`FFLAGS="-DMIST=0 -DPADOVA=1 -DMILES=0 -DBASEL=1" python -m pip install fsps --no-binary fsps`

to switch the libraries.

I tried installing with the `--no-binary` flag and dropping the `FFLAGS` just to see if it can compile at all, I get

```
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fsps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fsps\__init__.py", line 21, in <module>
    from .fsps import StellarPopulation  # noqa
  File "C:\Users\xxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fsps\fsps.py", line 8, in <module>
    from ._fsps import driver
ImportError: DLL load failed while importing _fsps: %1 is not a valid Win32 application.
```

Thanks!

**Comment by dfm** [comment]
> It is not possible to use

You'll need to set the `FFLAGS` environment variable however you do such a thing in pwsh. I don't have any experience with that, but that value for the flag should also work on Windows. Then after setting that, just run:

```bash
python -m pip install fsps --no-binary fsps
```

Removing the `--no-binary` isn't what you want.
